### PR TITLE
Feature/Showing optional gradient on bitmap

### PR DESCRIPTION
**Pull request by kmalmur**
Added a new feature to the library, making possible to cast a color shadow to the displayed image

### CODE REVIEW

**Review by blipinsk — CHANGES_REQUESTED** [review]
The code looks good, the only problem I have is the naming. You're not really casting any shadows there. Can we rename it to e.g. `smoothColorTransition` (or something similar)?

**Comment by kmalmur** [comment]
[Update layout notification to allow text showing](https://trello.com/c/GVWEaZCY/250-update-layout-notification-to-allow-text-showing)

**Comment by kmalmur** [comment]
@blipinsk changes implemented

**Review by blipinsk — APPROVED** [review]

**Comment by blipinsk** [comment]
@kmalmur approved

**Pull request merged**
